Manage experiment Phase and show surveys.
mozilla/pioneer-study-online-news pull request #18
Opened 2017-10-20 20:54 UTC by mythmon

This adds a list of phases to `Config.jsm`, and advances through them on schedule. "Surveys" are shown at the beginning of each phase. Right now the timer is really fast for testing purposes. We'll probably need to slow this down, but it really helps in verifying this PR.

2017-11-01 15:38 UTC, rehandalal requested changes
some small changes

2017-11-01 15:38 UTC, rehandalal commented on extension/Config.jsm
> +  schemaVersion: 1,
we don't need this any more sing this is ping specific

2017-11-01 15:38 UTC, rehandalal commented on extension/Config.jsm
> +  studyName: "news",
this should be `"online-news"`

2017-11-01 15:38 UTC, rehandalal commented on extension/Config.jsm
> +      duration: 5000, // 3 * WEEK,
should we have the actual values in here and comment out the test values?

2017-11-01 15:38 UTC, rehandalal commented on extension/Config.jsm
> +      duration: 5000, // 3 * WEEK,
same for the rest below.

2017-11-01 15:38 UTC, rehandalal commented on extension/lib/Phases.jsm
> +  // TODO this should be from pioneer-utils
I'll have a PR with this up shortly.

2017-11-02 17:46 UTC, mythmon commented on package.json
> -    "pioneer-studies-addon-utils": "1.0.1"
Because we have a `package-lock.json`, using semver versions instead of pinning here is the correct thing to do.

2017-11-02 17:47 UTC, mythmon commented
I think this is ready to go now.

2017-11-02 18:10 UTC, rehandalal approved these changes
r+. awesome work!

2017-11-02 18:10 UTC, merged